# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('avatar', models.CharField(default='static/images/default.png', max_length=50)),
                ('content', models.TextField()),
                ('create_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
