# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
