# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20180809_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='static/images/default.png', max_length=100),
        ),
    ]
