# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField()),
                ('favs', models.IntegerField()),
                ('createtime', models.DateField()),
            ],
        ),
    ]
