# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180802_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('createtime', models.DateField(auto_now=True)),
            ],
        ),
    ]
