# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_comment_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='/static/images/default.png', max_length=250),
        ),
    ]
