# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20170801_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('男', 'boy'), ('女', 'girl')], max_length=10),
        ),
    ]
