# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20170802_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('boy', '男'), ('girl', '女')], max_length=10),
        ),
    ]
