# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20170802_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='belong_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('girl', '女'), ('boy', '男')], max_length=10),
        ),
    ]
