# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_aritcle_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aritcle',
            name='tag',
        ),
    ]
