# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-12 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20161107_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
