# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180808_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
    ]
